project_id = "yjctmsivcaouvehmxtkc"

[functions.jailbreak-test]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.get-user-email]
verify_jwt = false

[functions.update-user-credentials]
verify_jwt = true